SELECT CDEMPRESA FROM TSIM_PROD_X_EMPRESA WHERE CDPRODUCTO = '01' AND PSVENTA = (select MIN(PSVALOR) FROM TSIM_PROD_X_EMPRESA) LIMIT 1;


SELECT * FROM TSIM_PRODUCTOS;

SET SERVEROUTPUT ON;
EXECUTE SP_CAMBIO_VALOR_PROD();
